id: I2E9AF9F5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T18:34:05+00:00'
last_modified: '2022-06-09T04:30:56.127513+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137882
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་བློ་གསལ་བློའི་པདྨོ་ཁ་འབྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4BD7:
      image_group_id: I1KG15930
      title: Volume 1 of dam pa'i chos mngon pa mdzod kyi rnam bshad blo gsal blo'i
        pad+mo kha 'byed/
      total_pages: 502
      order: 1
      base_file: 4BD7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
