id: P007067
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137882
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་བློ་གསལ་བློའི་པདྨོ་ཁ་འབྱེད།
  author: ''
  volumes:
    e04030a1f7404c3dae86c58f7ca85168:
      image_group_id: I1KG15930
      title: ''
      volume_number: 1
      total_pages: 502
ebook_metadata:
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་བློ་གསལ་བློའི་པདྨོ་ཁ་འབྱེད།
  author: ''
  sku: P007067
  cover: cover.jpg
  layers:
  - pagination
